# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/android'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'MotionStudioRuby'

  app.api_version = "21"
  app.development {
   app.archs << "x86" # for genymotion support
  }

  app.gradle do
    repository 'https://bintray.com/bintray/jcenter'
    repository 'https://dl.bintray.com/realm/maven'
    repository 'http://dl.bintray.com/austintaylor/gradle'

    compile project(':motionstudiolib') # ideal imaginary project dependency. see MotionStudio/app/build.gradle
  end

end
